// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/be-feedback_help/grpc"
	"github.com/asynccnu/be-feedback_help/ioc"
	"github.com/asynccnu/be-feedback_help/pkg/grpcx"
	"github.com/asynccnu/be-feedback_help/repository"
	"github.com/asynccnu/be-feedback_help/repository/cache"
	"github.com/asynccnu/be-feedback_help/repository/dao"
	"github.com/asynccnu/be-feedback_help/service"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	daoDao := dao.NewFeedbackHelpGormDao(db)
	cmdable := ioc.InitRedis()
	cacheCache := cache.NewFeedbackHelpRedisCache(cmdable)
	helpRepository := repository.NewFeedbackHelpHelpRepository(daoDao, cacheCache)
	serviceService := service.NewFeedbackHelpService(helpRepository)
	feedbackHelpService := grpc.NewFeedbackHelpServiceServer(serviceService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxKratosServer(feedbackHelpService, client, logger)
	return server
}
