mysql:
  dsn: "root:1238564@tcp(localhost:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"


redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:2379"

grpc:
  server:
    name: "feedback_help"
    weight: 100
    addr: ":19086"
    etcdTTL: 60